// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/cubes/absorb": {
            "put": {
                "description": "- USR によってのみ使用できる\n- Cube に知識を追加する\n- 実行には AbsorbLimit に残数が必要",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "コンテンツを取り込む",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AbsorbCubeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/AbsorbCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/create": {
            "post": {
                "description": "- USR によってのみ使用できる\n- 作成者は「神権限 (Limit = 0: 無制限)」を持つ\n- Cube は知識ベースとして機能し、Absorb/Memify/Search を通じて利用される",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "新しいCubeを作成する。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateCubeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/CreateCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/delete": {
            "delete": {
                "description": "- USR によってのみ使用できる\n- 指定したCubeと関連データを完全に削除する",
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cubeを削除する (Delete)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cube ID",
                        "name": "cube_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/DeleteCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/export": {
            "get": {
                "description": "- USR によってのみ使用できる\n- Cube を .cube ファイルとしてダウンロードする\n- 実行には ExportLimit に残数が必要\n- 成功すると Zip ファイル (application/zip) が返却される",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cube をエクスポートする。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cube ID",
                        "name": "cube_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "cube_uuid.cube",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/genkey": {
            "post": {
                "description": "- USR によってのみ使用できる\n- Exportされた.cubeファイルをアップロードして鍵を発行\n- 発行される鍵には権限と有効期限が含まれる",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "鍵を発行する",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": ".cube file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CubePermission JSON",
                        "name": "permissions",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "有効期限 (ISO8601)",
                        "name": "expire_at",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/GenKeyCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/get/{cube_id}": {
            "get": {
                "description": "- USR によってのみ使用できる\n- Cube の基本情報、統計、系譜情報を取得する",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cubeの詳細情報を取得",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cube ID",
                        "name": "cube_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/GetCubeRes"
                        }
                    },
                    "400": {
                        "description": "Validation Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/import": {
            "post": {
                "description": "- USR によってのみ使用できる\n- .cubeファイルと鍵を使用してCubeをインポート\n- 鍵に含まれる権限と有効期限が適用される",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cubeをインポートする",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": ".cube file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "鍵文字列",
                        "name": "key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新しいCube名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "説明",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ImportCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/memify": {
            "put": {
                "description": "- USR によってのみ使用できる\n- 指定したCubeの知識を強化・最適化する\n- memory_groupで対象分野を指定",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cubeを自己強化する (Memify)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/MemifyCubeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/MemifyCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/query": {
            "post": {
                "description": "- USR によってのみ使用できる\n- 指定したCubeの知識を利用してクエリに回答する\n- memory_groupで対象分野を指定\n---\n### クエリタイプ一覧\n| ID | Type | Description |\n|---|---|---|\n| 1 | QUERY_TYPE_GET_GRAPH | 知識グラフ自体を取得 |\n| 2 | QUERY_TYPE_GET_CHUNKS | ベクトル検索によりチャンクを取得 |\n| 3 | QUERY_TYPE_GET_PRE_MADE_SUMMARIES | 事前に作成された要約リストを取得 |\n| 4 | QUERY_TYPE_GET_GRAPH_AND_CHUNKS | 知識グラフとベクトル検索によるチャンクを取得 |\n| 5 | QUERY_TYPE_GET_GRAPH_AND_PRE_MADE_SUMMARIES | 知識グラフと事前に作成された要約リストを取得 |\n| 6 | QUERY_TYPE_GET_GRAPH_AND_CHUNKS_AND_PRE_MADE_SUMMARIES | 知識グラフとベクトル検索によるチャンクと事前に作成された要約リストを取得 |\n| 7 | QUERY_TYPE_GET_GRAPH_EXPLANATION_EN | 知識グラフを英語で構造文変換して取得 |\n| 8 | QUERY_TYPE_GET_GRAPH_EXPLANATION_JA | 知識グラフを日本語で構造文変換して取得 |\n| 9 | QUERY_TYPE_GET_GRAPH_SUMMARY_EN | 知識グラフを英語で要約文変換して取得 |\n| 10 | QUERY_TYPE_GET_GRAPH_SUMMARY_JA | 知識グラフを日本語で要約文変換して取得 |\n| 11 | QUERY_TYPE_GET_GRAPH_SUMMARY_TO_ANSWER_EN | 知識グラフを、クエリにダイレクトに答えられる形式の英語要約文で取得 |\n| 12 | QUERY_TYPE_GET_GRAPH_SUMMARY_TO_ANSWER_JA | 知識グラフを、クエリにダイレクトに答えられる形式の日本語要約文で取得 |\n| 13 | QUERY_TYPE_ANSWER_BY_PRE_MADE_SUMMARIES_AND_GRAPH_SUMMARY_EN | 事前に作成された要約リストと、知識グラフ要約を用いて質問に英語で回答 |\n| 14 | QUERY_TYPE_ANSWER_BY_PRE_MADE_SUMMARIES_AND_GRAPH_SUMMARY_JA | 事前に作成された要約リストと、知識グラフ要約を用いて質問に日本語で回答 |\n| 15 | QUERY_TYPE_ANSWER_BY_CHUNKS_AND_GRAPH_SUMMARY_EN | ベクトル検索によるチャンクと知識グラフ要約を用いて質問に英語で回答 |\n| 16 | QUERY_TYPE_ANSWER_BY_CHUNKS_AND_GRAPH_SUMMARY_JA | ベクトル検索によるチャンクと知識グラフ要約を用いて質問に日本語で回答 |",
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cubeにクエリを実行する (Query)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/QueryCubeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/QueryCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/rekey": {
            "post": {
                "description": "- USR によってのみ使用できる\n- 新しい鍵を使用して権限と有効期限を更新\n- ReKey対象のCubeはImportされたものである必要がある",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cubeの権限を更新する (ReKey)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ReKeyCubeParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/ReKeyCubeRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/cubes/search": {
            "post": {
                "description": "- USR によってのみ使用できる\n- 条件に一致するCubeの詳細情報を一覧取得する",
                "tags": [
                    "v1 Cube"
                ],
                "summary": "Cubeを検索",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Search Params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SearchCubesParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/SearchCubesRes"
                        }
                    },
                    "400": {
                        "description": "Validation Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/keys/check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Key"
                ],
                "summary": "鍵の一致を確認する。",
                "parameters": [
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CheckKeyHashParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/CheckKeyHashRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/keys/generate": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 Key"
                ],
                "summary": "鍵を生成する。",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/GenerateKeyHashRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/usrs/": {
            "post": {
                "description": "- Key で取得した token では Apx のみを作成できる\n- Apx で取得した token では Vdr のみを作成できる\n- Vdr で取得した token では Usr のみを作成できる\n- Usr は Usr を作れない\n### パラメータについて\n- type: 1: 法人, 2: 個人 (VDR作成時は無視される)\n- VDR作成時以外にVDR用項目を送信するとエラーとなる\n- 法人作成時以外に法人用項目を送信するとエラーとなる\n### name について\n- type=2 (個人) の場合、姓名の間にスペース（半角・全角問わず）が必須\n- 全角スペースは半角スペースに変換され、連続するスペースは1つにまとめられる",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "ユーザを作成する。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUsrParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/CreateUsrRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/usrs/auth/{apx_id}/{vdr_id}": {
            "get": {
                "description": "### 総則\n- X-Key での認証時は、X-Key を入れ、apx_id=0、vdr_id=0、email \u0026 password はダミーを入力\n- APX として認証する場合、apx_id=0、vdr_id=0、email \u0026 password は当該APXのもの\n- VDR として認証する場合、apx_id=所属ApxID、vdr_id=0、email \u0026 password は当該VDRのもの\n- USR として認証する場合、apx_id=所属ApxID、vdr_id=所属VdrID、email \u0026 password は当該USRのもの\n- expire は hour で指定すること\n### スタッフについて\n- USRは、VDR の権限により、VDRのスタッフになることができる\n- スタッフとしての立場を与えられた USRは、その後、スタッフとしての token のみを取得できる\n- スタッフ token を使用した場合、システム内で常に VDR として振る舞うことになる\n- その場合、全ての操作は当該 VDR が行ったものと同一の結果となる\n- 行った操作が、どのスタッフによるものか記録したい場合は、token payload 内の usr_id で記録できる\n- システム内部においては、ju.StaffID がそれにあたる\n### 注意\n- スタッフであるかどうかの確認は、tokenの取得のタイミングで1度だけ行われる\n- 取得した token が、スタッフであるか否かを示す唯一の証明書である\n- 当該 USR が真にスタッフであるかを問わず、システムは token によってのみスタッフか否かを判断する\n- つまり、スタッフ token を取得後、VDR により当該 USR がスタッフ権限を剥奪されたとしても、当該 token の expire までは、そのスタッフ token は有効である",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "認証を行い、tokenを返す。ロールや権限も一緒に返す。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "??????????",
                        "description": "key",
                        "name": "X-Key",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "apx_id",
                        "name": "apx_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "vdr_id",
                        "name": "vdr_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": 24,
                        "description": "expire",
                        "name": "expire",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/AuthUsrRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/usrs/search": {
            "post": {
                "description": "- Keyは全てのユーザを検索できる\n- Apxは配下のVdr以下の全てのユーザを検索できる\n- Vdrは、配下の全てのユーザを検索できる\n- Usr は使用できない",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "ユーザを検索する。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SearchUsrParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/SearchUsrsRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/usrs/{usr_id}": {
            "get": {
                "description": "- Keyは全てのユーザを取得できる\n- Apxは配下のVdr以下の全てのユーザを取得できる\n- Vdrは、配下の全てのユーザを取得できる\n- Usr は使用できない",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "ユーザ情報を1件取得する。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ユーザID",
                        "name": "usr_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/GetUsrRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            },
            "delete": {
                "description": "- Keyは安全の為、削除権限を持たない\n- Apxは配下のVdrのみを削除できる\n- Vdrは、配下の全てのユーザを削除できる\n- Usrは使用できない",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "ユーザを削除する。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ユーザID",
                        "name": "usr_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/DeleteUsrRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            },
            "patch": {
                "description": "- Keyは安全の為、更新権限を持たない\n- Apxは配下のVdr以下の全てのユーザを更新できる\n- Vdrは、配下の全てのユーザを更新できる\n- Usrは使用できない\n### パラメータについて\n- type: 1: 法人, 2: 個人 (更新時は変更不可の場合がある)\n- VDR以外にVDR用項目を送信するとエラーとなる\n- 法人以外に法人用項目を送信するとエラーとなる\n### name について\n- type=2 (個人) の場合、姓名の間にスペース（半角・全角問わず）が必須\n- 全角スペースは半角スペースに変換され、連続するスペースは1つにまとめられる",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "ユーザ情報を更新する。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ユーザID",
                        "name": "usr_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateUsrParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/UpdateUsrRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        },
        "/v1/usrs/{usr_id}/hire": {
            "delete": {
                "description": "- Vdr によってのみ使用できる\n- スタッフは Vdr として振る舞うため、同様に使用できる",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "ユーザからベンダーのスタッフとしての権限を剥奪する。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ユーザID",
                        "name": "usr_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/DehireUsrRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            },
            "patch": {
                "description": "- Vdr によってのみ使用できる\n- スタッフは Vdr として振る舞うため、同様に使用できる",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "v1 User"
                ],
                "summary": "ユーザにベンダーのスタッフとしての権限を与える。",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer ??????????",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ユーザID",
                        "name": "usr_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/HireUsrRes"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "AbsorbCubeParam": {
            "type": "object",
            "properties": {
                "chunk_overlap": {
                    "type": "integer",
                    "example": 16
                },
                "chunk_size": {
                    "type": "integer",
                    "example": 512
                },
                "content": {
                    "type": "string",
                    "example": "Knowledge base for Go development"
                },
                "cube_id": {
                    "type": "integer",
                    "example": 1
                },
                "memory_group": {
                    "type": "string",
                    "example": "legal_expert"
                }
            }
        },
        "AbsorbCubeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/AbsorbCubeResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "AbsorbCubeResData": {
            "type": "object",
            "properties": {
                "absorb_limit": {
                    "type": "integer"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                }
            }
        },
        "AuthUsrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/AuthUsrResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "AuthUsrResData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "???????????????"
                }
            }
        },
        "CheckKeyHashParam": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "????????????????"
                }
            }
        },
        "CheckKeyHashRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/CheckKeyHashResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "CheckKeyHashResData": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "ContributorRes": {
            "type": "object",
            "properties": {
                "contributor_name": {
                    "type": "string"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "model_name": {
                    "type": "string"
                },
                "output_tokens": {
                    "type": "integer"
                }
            }
        },
        "CreateCubeParam": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Knowledge base for Go development"
                },
                "embedding_api_key": {
                    "type": "string",
                    "example": "sk-proj-..."
                },
                "embedding_base_url": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "embedding_dimension": {
                    "type": "integer",
                    "example": 1536
                },
                "embedding_model": {
                    "type": "string",
                    "example": "text-embedding-3-small"
                },
                "embedding_provider": {
                    "type": "string",
                    "example": "openai"
                },
                "name": {
                    "type": "string",
                    "example": "My Cube"
                }
            }
        },
        "CreateCubeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/CreateCubeResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "CreateCubeResData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "CreateUsrParam": {
            "type": "object",
            "properties": {
                "bgn_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "sample@example.com"
                },
                "end_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2100-12-31T23:59:59"
                },
                "name": {
                    "type": "string",
                    "example": "User01"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "example": "ta5!CAzQz8DjMydju?"
                },
                "type": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "CreateUsrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/CreateUsrResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "CreateUsrResData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "DehireUsrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/DehireUsrResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "DehireUsrResData": {
            "type": "object"
        },
        "DeleteCubeRes": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "DeleteUsrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/DeleteUsrResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "DeleteUsrResData": {
            "type": "object"
        },
        "EmptyObj": {
            "type": "object"
        },
        "Err": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 100000
                },
                "field": {
                    "type": "string",
                    "example": "field_name"
                },
                "message": {
                    "type": "string",
                    "example": "Some Error Message"
                }
            }
        },
        "ErrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/EmptyObj"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "GenKeyCubeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/GenKeyCubeResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "GenKeyCubeResData": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "GenerateKeyHashRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/GenerateKeyHashResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "GenerateKeyHashResData": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string",
                    "example": "???????????"
                }
            }
        },
        "GetCubeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/GetCubeResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "GetCubeResData": {
            "type": "object",
            "properties": {
                "cube": {
                    "$ref": "#/definitions/rtres.GetCubeResCube"
                },
                "lineage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LineageRes"
                    }
                },
                "memory_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/MemoryGroupStatsRes"
                    }
                }
            }
        },
        "GetUsrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/GetUsrResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "GetUsrResData": {
            "type": "object",
            "properties": {
                "apx_id": {
                    "type": "integer",
                    "example": 1
                },
                "bgn_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "sample@example.com"
                },
                "end_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "User01"
                },
                "type": {
                    "type": "integer",
                    "example": 1
                },
                "vdr_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "HireUsrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/HireUsrResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "HireUsrResData": {
            "type": "object"
        },
        "ImportCubeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/ImportCubeResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "ImportCubeResData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "LineageRes": {
            "type": "object",
            "properties": {
                "exported_at": {
                    "description": "timestamp ms",
                    "type": "integer"
                },
                "exported_at_jst": {
                    "description": "YYYY-MM-DDThh:mm:ss (JST)",
                    "type": "string"
                },
                "generation": {
                    "type": "integer"
                },
                "owner": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "MemifyCubeParam": {
            "type": "object",
            "properties": {
                "cube_id": {
                    "type": "integer",
                    "example": 1
                },
                "epochs": {
                    "type": "integer",
                    "example": 1
                },
                "memory_group": {
                    "type": "string",
                    "example": "legal_expert"
                },
                "prioritize_unknowns": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "MemifyCubeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/MemifyCubeResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "MemifyCubeResData": {
            "type": "object",
            "properties": {
                "input_tokens": {
                    "type": "integer",
                    "example": 5000
                },
                "memify_limit": {
                    "type": "integer",
                    "example": -1
                },
                "output_tokens": {
                    "type": "integer",
                    "example": 2000
                }
            }
        },
        "MemoryGroupStatsRes": {
            "type": "object",
            "properties": {
                "contributors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ContributorRes"
                    }
                },
                "memory_group": {
                    "type": "string"
                },
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ModelStatRes"
                    }
                }
            }
        },
        "ModelStatRes": {
            "type": "object",
            "properties": {
                "action_type": {
                    "description": "\"training\" or \"search\"",
                    "type": "string"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "model_name": {
                    "type": "string"
                },
                "output_tokens": {
                    "type": "integer"
                }
            }
        },
        "QueryCubeParam": {
            "type": "object",
            "properties": {
                "chunk_topk": {
                    "type": "integer",
                    "example": 3
                },
                "cube_id": {
                    "type": "integer",
                    "example": 1
                },
                "entity_topk": {
                    "type": "integer",
                    "example": 3
                },
                "memory_group": {
                    "type": "string",
                    "example": "legal_expert"
                },
                "summary_topk": {
                    "type": "integer",
                    "example": 3
                },
                "text": {
                    "type": "string",
                    "example": "契約違反の場合の対処法は？"
                },
                "type": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "QueryCubeRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/QueryCubeResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "QueryCubeResData": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "契約違反の場合は..."
                },
                "chunks": {
                    "type": "string",
                    "example": "契約違反の場合は..."
                },
                "graph": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "input_tokens": {
                    "type": "integer",
                    "example": 1500
                },
                "output_tokens": {
                    "type": "integer",
                    "example": 500
                },
                "query_limit": {
                    "type": "integer",
                    "example": -1
                },
                "summaries": {
                    "type": "string",
                    "example": "契約違反の場合は..."
                }
            }
        },
        "ReKeyCubeParam": {
            "type": "object",
            "properties": {
                "cube_id": {
                    "type": "integer",
                    "example": 1
                },
                "key": {
                    "type": "string",
                    "example": "alknas38msd..."
                }
            }
        },
        "ReKeyCubeRes": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "SearchCubesParam": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Legal advisor"
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "name": {
                    "type": "string",
                    "example": "Legal Bot"
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "SearchCubesRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SearchCubesResData"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "SearchCubesResData": {
            "type": "object",
            "properties": {
                "cube": {
                    "$ref": "#/definitions/rtres.SearchCubesResCube"
                },
                "lineage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LineageRes"
                    }
                },
                "memory_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/MemoryGroupStatsRes"
                    }
                }
            }
        },
        "SearchUsrParam": {
            "type": "object",
            "properties": {
                "bgn_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "sample@example.com"
                },
                "end_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2100-12-31T23:59:59"
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "name": {
                    "type": "string",
                    "example": "User01"
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "SearchUsrsRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SearchUsrsResData"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "SearchUsrsResData": {
            "type": "object",
            "properties": {
                "apx_id": {
                    "type": "integer",
                    "example": 1
                },
                "bgn_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "sample@example.com"
                },
                "end_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "User01"
                },
                "type": {
                    "type": "integer",
                    "example": 1
                },
                "vdr_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "UpdateUsrParam": {
            "type": "object",
            "properties": {
                "bgn_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "sample@example.com"
                },
                "end_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2100-12-31T23:59:59"
                },
                "name": {
                    "type": "string",
                    "example": "User01"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "example": "ta5!CAzQz8DjMydju?"
                },
                "type": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "UpdateUsrRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/UpdateUsrResData"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Err"
                    }
                }
            }
        },
        "UpdateUsrResData": {
            "type": "object"
        },
        "rtres.GetCubeResCube": {
            "type": "object",
            "properties": {
                "apx_id": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-01-01T00:00:00"
                },
                "description": {
                    "type": "string",
                    "example": "This is my cube"
                },
                "embedding_base_url": {
                    "type": "string"
                },
                "embedding_dimension": {
                    "type": "integer"
                },
                "embedding_model": {
                    "type": "string"
                },
                "embedding_provider": {
                    "type": "string"
                },
                "expire_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-01-01T00:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "MyCube"
                },
                "permissions": {
                    "type": "string",
                    "example": "{}"
                },
                "source_export_id": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-01-01T00:00:00"
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "vdr_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "rtres.SearchCubesResCube": {
            "type": "object",
            "properties": {
                "apx_id": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-01-01T00:00:00"
                },
                "description": {
                    "type": "string",
                    "example": "This is my cube"
                },
                "embedding_base_url": {
                    "type": "string"
                },
                "embedding_dimension": {
                    "type": "integer"
                },
                "embedding_model": {
                    "type": "string"
                },
                "embedding_provider": {
                    "type": "string"
                },
                "expire_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-01-01T00:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "MyCube"
                },
                "permissions": {
                    "type": "string",
                    "example": "{}"
                },
                "source_export_id": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-01-01T00:00:00"
                },
                "uuid": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "vdr_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "MYCUTE",
	Description:      "## API概要\\nMYCUTE REST APIを定義する。\\nURL最大長のリスクを避ける為、検索は query parameter ではなく body json を使用する。\\nGin に SEARCH/QUERY method の実装がないため、検索を POST にて行う。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
