//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "matches")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub job_id: u32,
    pub from: u32,
    pub to: u32,
    pub status: u8,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub priority_score: Decimal,
    pub badge_count: u32,
    pub match_reason: u8,
    pub apx_id: u32,
    pub vdr_id: u32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
