//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "apps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub apx_id: i32,
    pub vdr_id: i32,
    pub identity_id: i32,
    pub global_app_id: Uuid,
    pub global_app_version: String,
    pub global_app_hash: String,
    pub name: String,
    pub layer: String,
    pub install_path: Option<String>,
    pub remote_url: Option<String>,
    pub properties: Option<Json>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub dev_public_key: Option<String>,
    pub manifest_data: Option<Json>,
    pub verifications: Option<Json>,
    pub verification_results_cache: Option<Json>,
    pub author: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identities::Entity",
        from = "Column::IdentityId",
        to = "super::identities::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Identities,
}

impl Related<super::identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Identities.def()
    }
}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
