//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "blacklists")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub target_pubkey: String,
    #[sea_orm(column_type = "Text")]
    pub evidence_json: String,
    pub crime_type: i32,
    pub observed_at: i64,
    pub prison_term_hours: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
