//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cube_model_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cube_id: i32,
    pub memory_group: String,
    pub model_name: String,
    pub action_type: String,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub apx_id: i32,
    pub vdr_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
