//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub corp_id: i32,
    pub name: String,
    pub description: String,
    pub max: i32,
    pub filled: i32,
    pub hour_price: i32,
    pub requirements: String,
    pub benefits: String,
    pub location: String,
    pub phone: String,
    pub max_badges: i32,
    pub work_bgn_at: Option<DateTime>,
    pub work_end_at: Option<DateTime>,
    pub open_at: Option<DateTime>,
    pub close_at: Option<DateTime>,
    pub apx_id: i32,
    pub vdr_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
