//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod apps;
pub mod bds;
pub mod blacklists;
pub mod ca_vote_allocated_summaries;
pub mod ca_vote_item_summaries;
pub mod cryptos;
pub mod forums;
pub mod identities;
pub mod lmgw_providers;
pub mod replace_items;
pub mod replaces;
pub mod settings;
pub mod stt_histories;
pub mod tickets;
pub mod usrs;
pub mod verifications;
