//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod apps;
pub mod badges;
pub mod bds;
pub mod belongs;
pub mod blacklists;
pub mod burned_keys;
pub mod ca_vote_allocated_summaries;
pub mod ca_vote_item_summaries;
pub mod cryptos;
pub mod cube_contributors;
pub mod cube_lineages;
pub mod cube_model_stats;
pub mod cubes;
pub mod exports;
pub mod flushes;
pub mod forums;
pub mod identities;
pub mod jobs;
pub mod lmgw_providers;
pub mod match_statuses;
pub mod matches;
pub mod payments;
pub mod payouts;
pub mod points;
pub mod pools;
pub mod replace_items;
pub mod replaces;
pub mod settings;
pub mod tickets;
pub mod usr_badges;
pub mod usrs;
pub mod verifications;
pub mod works;
