//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payouts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pool_id: i32,
    pub flush_id: i32,
    pub usr_id: i32,
    pub points: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 5)))")]
    pub share: Decimal,
    pub amount: i32,
    pub apx_id: i32,
    pub vdr_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
