//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "usr_badges")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub badge_id: i32,
    pub corp_id: i32,
    pub from: i32,
    pub to: i32,
    pub title: String,
    pub message: String,
    pub r#type: i8,
    pub apx_id: i32,
    pub vdr_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
