//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "usrs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub r#type: i8,
    pub points: i32,
    pub sum_p: i32,
    pub sum_c: i32,
    pub email: String,
    pub password: String,
    pub zitadel_id: Option<String>,
    pub email_verified: bool,
    pub flush_days: i32,
    pub badged: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 5)))")]
    pub rate: Decimal,
    pub total_badged: i32,
    pub total_badges: i32,
    pub base_point: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 5)))")]
    pub belong_rate: Decimal,
    pub max_works: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 5)))")]
    pub flush_fee_rate: Decimal,
    pub is_staff: bool,
    pub bgn_at: DateTime,
    pub end_at: DateTime,
    pub apx_id: Option<i32>,
    pub vdr_id: Option<i32>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
