//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "verifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub node_pubkey: String,
    pub ca_pubkey: String,
    pub ca_base_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub signature: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ca_token: Option<String>,
    pub is_candidate: i8,
    pub verified_at: Option<DateTime>,
    pub expire_at: Option<DateTime>,
    pub applied_expire_seconds: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// impl ActiveModelBehavior for ActiveModel {}
crate::impl_utc_timestamp_behavior!(ActiveModel);
