import { CalendarEvent, User, type Card } from 'src/models/main'
import { PUBLIC_PATH } from 'src/configs/settings'
import { UsrType } from 'src/enums/usrtype'

const SAMPLE_NAMES = [
  "バイタルサイン測定", "注射・点滴スキル", "採血データ管理", "感染対策スキル", "褥瘡予防・ケア",
  "モニター装着・記録", "患者搬送支援", "呼吸管理スキル", "排泄ケア", "食事介助・経管栄養",
  "服薬管理", "転倒・転落予防", "ナースコール対応", "看護記録作成", "認知症ケア",
  "疼痛管理", "感染症患者対応", "小児看護技術", "高齢者ケア技術", "褥瘡アセスメント",
  "救急対応スキル", "心肺蘇生技術", "人工呼吸器管理", "感染症マニュアル遵守", "リーダーシフト管理",
  "他職種連携", "患者家族対応", "認知症リハビリ補助", "経過観察記録", "複数患者の優先順位管理",
  "体位変換技術", "口腔ケアスキル", "退院支援能力", "緊急カンファレンス対応", "記録の法的遵守",
  "医療安全管理", "医療機器チェック", "アセスメント能力", "認知症予防活動", "感染経路遮断",
  "看護教育指導", "感染症報告スキル", "看取り援助", "災害時対応力", "倫理的判断力",
  "外国人患者対応", "複雑ケース管理", "家族会議スキル", "多職種合同記録", "栄養管理チーム連携"
]

const SAMPLE_SHORT_NAMES = [
  "バイタル", "注射", "採血", "感染対策", "褥瘡ケア", "モニター管理", "搬送", "呼吸管理", "排泄ケア", "食事・栄養",
  "服薬", "転倒予防", "コール対応", "記録", "認知症", "疼痛管理", "感染患者", "小児看護", "高齢者", "褥瘡評価",
  "救急対応", "心肺蘇生", "呼吸器管理", "感染手順", "リーダー", "連携", "家族対応", "リハ補助", "経過記録", "優先順位",
  "体位変換", "口腔ケア", "退院支援", "カンファ", "法的遵守", "安全管理", "機器チェック", "アセスメント", "予防活動", "遮断",
  "教育指導", "感染報告", "看取り", "災害対応", "倫理判断", "外国人対応", "ケース管理", "家族会議", "合同記録", "栄養連携"
]

const SAMPLE_TITLES = [
  "患者第一の姿勢が際立つ",
  "想定外でも的確に対応",
  "細部まで配慮が行き届く",
  "安全意識向上に貢献",
  "冷静な判断で現場をリード",
  "丁寧な説明が好評でした",
  "多職種連携が見事でした",
  "改善への取り組み姿勢が模範的",
  "後輩指導で頼もしい存在",
  "災害訓練で中心的役割",
  "観察力の鋭さが光る",
  "感染対策の徹底ぶり",
  "記録の質が秀逸です",
  "夜勤帯での安定感",
  "家族ケアまで手厚く",
  "業務効率化に尽力",
  "褥瘡予防が完璧でした",
  "薬剤管理の正確さ",
  "新人教育が丁寧で的確",
  "緊急時の対応力が抜群",
  "委員会活動で主導的",
  "患者満足度に直結",
  "チームワーク向上に貢献",
  "リスク予測能力が高い",
  "傾聴姿勢が素晴らしい",
  "医療機器操作が熟練",
  "看護研究への意欲",
  "退院支援が手厚い",
  "認知症ケアが適切",
  "ターミナルケアの配慮"
];

const SAMPLE_BODIES = [
  (detail: string) =>
    `【${detail}】を担当された際、患者さん一人ひとりの状態を正確に把握し、最適なケア方法を選択されていました。リスクマネジメントの観点からも、状況ごとの判断力が他のスタッフに安心感を与えていました。事例ごとの記録も非常に丁寧で、将来の参考にもなりました。`,
  (detail: string) =>
    `今回の${detail}では、予想外かつ急な場面にも冷静に対応され、先を見据えた行動が素晴らしかったです。患者さんやご家族に必要な説明もすぐに行い、不安軽減にも繋げられました。チーム内での情報共有も的確でした。`,
  (detail: string) =>
    `日々の${detail}業務において、観察力と洞察力が卓抜しており、細部まで心配りが行き届いていました。患者さんの小さな変化も見逃さず、先回りしたケアが他職種スタッフにも良い影響を与えていました。`,
  (detail: string) =>
    `${detail}の場面では、標準予防策・安全確認・ヒヤリハット共有の意識が高く、院内全体にその姿勢が伝わっていました。さらに、改善案の提案や積極的なフィードバックも印象的で、業務全体の質向上に貢献してくれました。`,
  (detail: string) =>
    `${detail}対応時、複数の業務を同時に抱えながらも、的確な優先順位判断と迅速な行動が際立っていました。急変時も冷静に対応され、患者さんとご家族に安心感を与えていました。`,
  (detail: string) =>
    `患者さんやご家族から「とても丁寧な説明ありがとうございます」との声が多数ありました。${detail}実施時にも分かりやすい言葉で説明を心掛け、その結果不安感の軽減や満足度向上に寄与していると感じました。`,
  (detail: string) =>
    `他職種（医師、薬剤師、介護士）との情報交換や業務調整を積極的に行い、${detail}を円滑に進めることができました。その姿勢が、現場全体の協働をより強固なものにしています。`,
  (detail: string) =>
    `${detail}に関し、自主的な振り返り活動と改善への取り組みがとても印象的でした。既存の方法に満足せず、常により良いケアを目指している姿勢が多くのスタッフの模範となっています。`,
  (detail: string) =>
    `後輩スタッフが${detail}を行う場面で、的確な助言やフォローを惜しみなく行っていました。経験を活かした現場指導は、後輩に自信と成長の機会を与えてくれています。`,
  (detail: string) =>
    `災害対応訓練時、${detail}を中心的に担当し、全体の動きの指揮も見事でした。危機対応力と事前準備の丁寧さが、現場全体の質向上に繋がっています。今後もリーダー役として期待しています。`,
  (detail: string) =>
    `${detail}における観察スキルが際立っており、わずかなバイタルサインの変動や顔色の変化も見逃さず、早期対応に繋げられていました。アセスメント能力の高さと迅速な報告連絡相談の徹底により、医師からの信頼も厚く、患者さんの安全確保に大きく貢献されています。`,
  (detail: string) =>
    `${detail}での感染予防対策の実践が完璧でした。手指衛生のタイミング、防護具の適切な使用、ゾーニングの徹底など、マニュアルを遵守しつつ状況に応じた柔軟な対応も見事です。他スタッフへの声掛けや指導も自然に行われ、病棟全体の感染管理レベル向上に寄与しています。`,
  (detail: string) =>
    `${detail}に関する看護記録が極めて詳細かつ正確で、SOAPの構成も理路整然としていました。客観的データと主観的情報のバランスが良く、経過が一目で把握できる記述は、夜勤者への申し送りやカンファレンスでも高く評価されています。記録の質がケアの質に直結していることを体現されています。`,
  (detail: string) =>
    `夜勤帯での${detail}対応が非常に安定しており、少人数体制でも的確な判断と効率的な動線で業務を遂行されていました。急変対応時の落ち着いた態度と迅速な初期対応は、他スタッフの心強い支えとなっています。夜勤明けの申し送りも簡潔かつ要点を押さえており、日勤帯への引継ぎが非常にスムーズです。`,
  (detail: string) =>
    `${detail}において、患者さん本人だけでなく、ご家族の精神的サポートまで手厚く行われていました。面会時の丁寧な病状説明、不安や疑問への傾聴、療養環境の提案など、家族全体を看護の対象として捉える視点が素晴らしく、「この病棟で本当に良かった」との感謝の言葉を多数いただいています。`,
  (detail: string) =>
    `${detail}業務の効率化に関する提案と実践が印象的でした。物品配置の見直し、記録システムの活用方法、タイムマネジメントの工夫など、具体的な改善策を提示し実行されています。その結果、残業時間の削減と患者ケアの質向上を両立させ、働きやすい職場環境づくりに大きく貢献されました。`,
  (detail: string) =>
    `${detail}ケアにおける褥瘡予防対策が完璧でした。リスクアセスメントツールの適切な使用、体位変換スケジュールの徹底、栄養状態の評価、皮膚観察の細やかさなど、総合的なアプローチが見事です。褥瘡発生ゼロの実績は、あなたの丁寧なケアと予防意識の賜物です。`,
  (detail: string) =>
    `${detail}における薬剤管理の正確性が際立っていました。処方内容の確認、配薬時の6R確認、内服介助時の観察、副作用モニタリング、残薬管理まで、一連の流れが完璧です。インシデント防止への高い意識と、薬剤師との綿密な連携により、患者さんの安全な薬物療法に貢献されています。`,
  (detail: string) =>
    `新人スタッフへの${detail}教育が非常に丁寧で的確でした。技術指導時の段階的な説明、実践後の振り返り、ポジティブフィードバックと改善点の明確化など、教育手法が洗練されています。新人からは「優しく厳しく教えてくれる先輩」として慕われており、人材育成の重要な担い手となっています。`,
  (detail: string) =>
    `${detail}時の緊急対応能力が抜群でした。心肺停止や急変時の一次救命処置、応援要請のタイミング、医師への簡潔な状況報告、必要物品の準備など、すべてが迅速かつ的確です。BLSとACLSの知識を実践に活かす力は、チーム全体の救命力向上に大きく寄与しています。`,
  (detail: string) =>
    `委員会活動における${detail}への取り組みが主導的で素晴らしかったです。課題抽出から解決策の立案、実践、評価まで、PDCAサイクルを確実に回されています。他部署との調整力やプレゼンテーション能力も高く、病院全体の質向上に向けたリーダーシップを発揮されています。`,
  (detail: string) =>
    `${detail}における患者満足度向上への貢献が顕著でした。入院時オリエンテーションの丁寧さ、日常的なコミュニケーションの温かさ、要望への迅速な対応など、患者さん視点に立った行動が一貫しています。満足度調査での高評価や感謝の手紙は、あなたの人間性とプロ意識の現れです。`,
  (detail: string) =>
    `${detail}を通じたチームワーク向上への貢献が印象的でした。メンバー間の情報共有促進、困難事例でのサポート、雰囲気作りへの配慮など、チームの結束力を高める行動が自然にできています。あなたの存在がチーム全体の士気を上げ、協働する喜びを実感させてくれています。`,
  (detail: string) =>
    `${detail}場面でのリスク予測能力の高さが光りました。転倒転落、誤嚥、せん妄など、起こりうるリスクを事前に察知し、予防的介入を実施されています。環境整備や見守り体制の調整、多職種への情報提供など、先を見通した行動が患者さんの安全を守っています。`,
  (detail: string) =>
    `${detail}における傾聴姿勢が本当に素晴らしいです。患者さんの訴えに耳を傾ける姿勢、相槌や表情での共感表現、言葉にならない思いを汲み取る力など、コミュニケーション技術が卓越しています。患者さんが「この人になら話せる」と信頼を寄せる様子から、あなたの人間力の高さが伝わってきます。`,
  (detail: string) =>
    `${detail}に関する医療機器操作の熟練度が際立っていました。輸液ポンプ、人工呼吸器、心電図モニターなど、各種機器の正確な操作と異常時の対応が完璧です。定期点検やトラブルシューティングの知識も豊富で、MEとの連携も円滑です。安全で確実な医療提供の要となっています。`,
  (detail: string) =>
    `${detail}をテーマにした看護研究への意欲と実践が素晴らしいです。文献検索、研究計画立案、データ収集・分析、学会発表準備など、一連のプロセスに真摯に取り組まれています。エビデンスに基づく看護実践への探究心は、現場の看護の質向上と自己成長の両面で大きな意義があります。`,
  (detail: string) =>
    `${detail}における退院支援の手厚さが印象的でした。早期からの退院計画立案、患者・家族への指導、地域連携室やケアマネジャーとの調整、退院後の生活環境整備まで、シームレスな支援を実践されています。患者さんが安心して自宅に帰れるよう尽力する姿勢は、地域包括ケアの理想形です。`,
  (detail: string) =>
    `${detail}での認知症ケアが非常に適切でした。パーソンセンタードケアの視点で患者さんの背景や価値観を理解し、その人らしさを尊重したケアを提供されています。行動心理症状への対応、環境調整、家族支援など、総合的なアプローチが見事で、患者さんの穏やかな表情がその成果を物語っています。`,
  (detail: string) =>
    `${detail}におけるターミナルケアの配慮が心に残りました。症状マネジメント、意思決定支援、家族の心理的サポート、グリーフケアまで、患者さんとご家族に寄り添う姿勢が一貫しています。最期の時間を大切に過ごせるよう尽くす献身的な看護は、私たちが目指すべき看護の本質を体現しています。`
];

const FROM_CANDIDATES = [5, 6, 7, 8, 9, 10]

const SAMPLE_DESCRIPTIONS = [
  "患者の体温・血圧・脈拍・呼吸数を正確に測定できる", "静脈注射・皮下注射・点滴管理が安全に行える", "検査用の採血とデータ記録が的確に実施できる", "手指消毒・感染隔離・予防対策の知識と実践", "ポジショニング・スキンケアによる褥瘡予防",
  "心電図ECG・SpO2モニターの装着と記録", "安全な車椅子・ストレッチャー搬送技術", "酸素療法・吸引・マスク交換など呼吸管理技術", "オムツ交換・膀胱留置カテーテル・排便コントロール", "食事介助・経鼻胃管・胃瘻管理の知識と実技",
  "内服薬・外用薬・注射薬の管理と説明", "リスク評価と環境調整による転倒防止スキル", "迅速・適切な患者対応力と報告連携", "電子カルテ・記録用紙への正確な記録力", "認知症患者への対応とコミニュケーション",
  "鎮痛薬の投与・問診による痛み管理", "COVID等の感染患者対応とマニュアル順守", "小児患者への配慮・ケア技術", "加齢による身体特性への配慮とケア技術", "褥瘡の観察・評価・報告方法",
  "急変時のバイタル確認・応急処置技術", "BLS, AEDの使用・人工呼吸・胸骨圧迫", "人工呼吸器の設定・安全確認・トラブル対応", "標準予防策の徹底・手順マスター", "看護師業務の整理と効率的指導技術",
  "医師・薬剤師・介護士との連携スキル", "家族への状況説明・メンタルケア技術", "リハビリ計画の補助参加・ADL支援", "患者の経過観察と定期記録技術", "対象患者の緊急度・優先度の迅速判断",
  "安全な体位変換と患者の快適維持技術", "清潔な口腔ケア・口腔内観察判断", "退院時の計画書作成・各種説明スキル", "緊急時の多職種カンファレンス調整", "看護記録に関する法的記載・情報漏洩防止",
  "安全対策・ヒヤリハット報告・リスク管理技術", "点検・事故防止のための機器管理チェック", "患者状態・リスクの多面的観察技術", "認知症予防プログラム実施・評価技術", "感染経路遮断と環境調整技術",
  "新人・後輩への看護教育・現場指導能力", "院内感染症の発生時報告と各種対応", "終末期患者の看取り援助・家族サポート", "災害時のトリアージ・物資確保・患者管理", "現場での倫理判断・患者の権利尊重",
  "通訳・文化的背景理解を含む外国人への看護", "精神疾患・難病等の複雑症例管理", "意見集約・家族会議の進行支援技術", "医師等との多職種合同記録作成スキル", "NST（栄養サポートチーム）との連携実践"
]

export const SAMPLE_USERS: User[] = [
  {
    id: 1,
    first_name: "颯太",
    last_name: "斉藤",
    apx_id: 1,
    vdr_id: 1,
    type: UsrType.Indi,
    email: "souta.saito@example.com",
    exp: 1250,
    is_staff: false
  },
  {
    id: 2,
    first_name: "美月",
    last_name: "高橋",
    apx_id: 1,
    vdr_id: 1,
    type: UsrType.Indi,
    email: "mizuki.takahashi@example.com",
    exp: 3420,
    is_staff: false
  },
  {
    id: 3,
    first_name: "凛",
    last_name: "松本",
    apx_id: 1,
    vdr_id: 1,
    type: UsrType.Indi,
    email: "rin.matsumoto@example.com",
    exp: 890,
    is_staff: false
  },
  {
    id: 4,
    first_name: "陸斗",
    last_name: "中村",
    apx_id: 1,
    vdr_id: 1,
    type: UsrType.Indi,
    email: "rikuto.nakamura@example.com",
    exp: 5670,
    is_staff: false
  },
  {
    id: 5,
    first_name: "葵",
    last_name: "佐々木",
    apx_id: 1,
    vdr_id: 1,
    type: UsrType.Indi,
    email: "aoi.sasaki@example.com",
    exp: 2180,
    is_staff: false
  },
  {
    id: 6,
    first_name: "陽菜",
    last_name: "伊藤",
    apx_id: 1,
    vdr_id: 1,
    type: UsrType.Indi,
    email: "hina.ito@example.com",
    exp: 4560,
    is_staff: false
  }
]

export const SAMPLE_USERS_BY_ID: { [id: number]: User } = (() => {
  const rtn: { [id: number]: User } = {}
  SAMPLE_USERS.forEach(u => {
    rtn[u.id] = u
  })
  return rtn
})()

export const SAMPLE_USER_ID = 4

export const SAMPLE_USER_NAME = '山田花子'

export const SAMPLE_EVENTS: CalendarEvent[] = [
  {
    "id": 1,
    "img": `${PUBLIC_PATH}/sample-img/01.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/01-small.jpg`,
    "title": "新宿メディカルセンター",
    "subtitle": "一般外来補助、バイタル測定、採血、健康相談",
    "start": "2025-10-02T09:00:00",
    "end": "2025-10-02T17:00:00",
    "hourPrice": 1550,
    "description": "新宿駅近くの大型診療所です。外来補助や採血など看護師としての一般的な業務全般を担当いただきます。若いスタッフが多く、風通しの良い職場環境です。",
    "requirements": "看護師資格、外来経験歓迎",
    "benefits": "交通費全支給、制服貸与、研修充実",
    "location": "東京都新宿区西新宿2-10-3",
    "phone": "03-2345-6789",
    "maxBadges": 6,
    "isFixed": true
  },
  {
    "id": 2,
    "img": `${PUBLIC_PATH}/sample-img/02.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/02-small.jpg`,
    "title": "あさひクリニック",
    "subtitle": "夜間救急受付、点滴準備、問診、カルテ整理",
    "start": "2025-10-06T09:00:00",
    "end": "2025-10-06T17:00:00",
    "hourPrice": 1350,
    "description": "急病対応も行うクリニックです。夜間シフトあり、救急スキルも身につきます。アットホームな雰囲気が魅力です。",
    "requirements": "准看護師以上、夜勤可能な方歓迎",
    "benefits": "夜勤手当あり、週1日から勤務OK、無料駐車場",
    "location": "神奈川県横浜市神奈川区六角橋2-30-8",
    "phone": "045-8765-4321",
    "maxBadges": 2,
    "isFixed": false
  },
  {
    "id": 3,
    "img": `${PUBLIC_PATH}/sample-img/03.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/03-small.jpg`,
    "title": "さくら耳鼻咽喉科",
    "subtitle": "診察サポート、器具洗浄、受付、各種検査補助",
    "start": "2025-10-07T09:00:00",
    "end": "2025-10-07T17:00:00",
    "hourPrice": 1400,
    "description": "地域密着型の耳鼻科クリニックです。耳鼻科未経験者にも丁寧な指導を実施しています。",
    "requirements": "看護師または准看護師、有資格者のみ",
    "benefits": "交通費支給、残業ほぼなし、制服貸与",
    "location": "埼玉県さいたま市大宮区桜木町3-2-8",
    "phone": "048-1234-5678",
    "maxBadges": 3,
    "isFixed": true
  },
  {
    "id": 4,
    "img": `${PUBLIC_PATH}/sample-img/04.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/04-small.jpg`,
    "title": "和光リハビリ病院",
    "subtitle": "リハビリ補助、患者搬送、服薬管理、健康測定",
    "start": "2025-10-28T09:00:00",
    "end": "2025-10-28T17:00:00",
    "hourPrice": 1600,
    "description": "リハビリ病院でのお仕事です。患者さんとじっくり向き合いながら仕事ができます。チームでの協力体制を大切にしています。",
    "requirements": "正看護師資格、リハビリ施設経験者歓迎",
    "benefits": "無料託児所あり、交通費支給、昇給あり",
    "location": "東京都練馬区光が丘5-17-12",
    "phone": "03-5678-9999",
    "maxBadges": 8,
    "isFixed": false
  },
  {
    "id": 5,
    "img": `${PUBLIC_PATH}/sample-img/05.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/05-small.jpg`,
    "title": "みどり健康診断センター",
    "subtitle": "健診受付、問診、心電図・採血補助、記録業務",
    "start": "2025-10-29T09:00:00",
    "end": "2025-10-29T17:00:00",
    "hourPrice": 1450,
    "description": "企業や学校向けの健康診断センターです。受付対応や検査補助、スタッフ同士の連携も良く、未経験からでも安心して働けます。",
    "requirements": "看護師資格、健診業務経験者歓迎",
    "benefits": "健診手当、昼食補助、交通費支給",
    "location": "千葉県千葉市中央区登戸1-5-17",
    "phone": "043-234-5678",
    "maxBadges": 5,
    "isFixed": false
  }
]

export const SAMPLE_CARDS: Card[] = [
  {
    "id": 6,
    "img": `${PUBLIC_PATH}/sample-img/02.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/02-small.jpg`,
    "title": "山田総合病院",
    "subtitle": "外来バイタル測定、採血、注射、問診補助",
    "start": "2025-10-09T09:00:00",
    "end": "2025-10-09T17:00:00",
    "hourPrice": 1500,
    "description": "当院は地域密着型の総合病院として、幅広い診療科目を持つ医療機関です。外来診療において、患者様のバイタル測定から採血・注射業務まで、基本的な看護業務をお任せします。経験豊富なスタッフがサポートしますので、ブランクのある方も安心してご応募ください。",
    "requirements": "正看護師資格必須、外来経験1年以上歓迎",
    "benefits": "交通費全額支給、白衣貸与、駐車場無料",
    "location": "東京都世田谷区桜新町2-15-8",
    "phone": "03-1234-5678",
    "maxBadges": 7,
    "isFixed": false
  },
  {
    "id": 7,
    "img": `${PUBLIC_PATH}/sample-img/03.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/03-small.jpg`,
    "title": "田中内科医院",
    "subtitle": "夜間受付補助、点滴準備、患者対応、カルテ整理",
    "start": "2025-10-12T18:00:00",
    "end": "2025-10-12T23:30:00",
    "hourPrice": 1700,
    "description": "夜間診療を行うクリニックでの勤務です。受付業務のサポートから点滴準備、患者様対応まで、幅広い業務に携わっていただきます。夜勤手当が充実しており、効率よく稼ぎたい方に最適です。少人数のアットホームな職場環境が魅力です。",
    "requirements": "正看護師資格、夜勤対応可能な方",
    "benefits": "夜勤手当あり、食事補助、週1回～OK",
    "location": "神奈川県横浜市港北区日吉3-22-1",
    "phone": "045-987-6543",
    "maxBadges": 6,
    "isFixed": false
  },
  {
    "id": 8,
    "img": `${PUBLIC_PATH}/sample-img/04.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/04-small.jpg`,
    "title": "鈴木耳鼻科クリニック",
    "subtitle": "診察介助、器具洗浄、患者案内、検査補助",
    "start": "2025-10-15T09:00:00",
    "end": "2025-10-15T17:00:00",
    "hourPrice": 1300,
    "description": "地域に根ざした耳鼻科クリニックです。診察介助や医療器具の洗浄・滅菌、患者様の案内など、クリニック全体の運営をサポートしていただきます。耳鼻科未経験の方も丁寧に指導いたしますので、新しい分野にチャレンジしたい方を歓迎します。",
    "requirements": "正看護師または准看護師資格",
    "benefits": "残業ほぼなし、有給消化率高、制服貸与",
    "location": "埼玉県さいたま市大宮区桜木町1-7-5",
    "phone": "048-765-4321",
    "maxBadges": 2,
    "isFixed": false
  },
  {
    "id": 9,
    "img": `${PUBLIC_PATH}/sample-img/05.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/05-small.jpg`,
    "title": "山田総合病院",
    "subtitle": "病棟看護、記録入力、配薬準備、処置補助",
    "start": "2025-10-18T08:00:00",
    "end": "2025-10-18T19:00:00",
    "hourPrice": 1200,
    "description": "病棟での看護業務全般をお願いします。電子カルテへの記録入力、配薬準備、医師の処置補助など、チーム医療の一員として活躍していただきます。教育体制が整っており、スキルアップを目指す方に最適な環境です。長期勤務希望の方は優遇いたします。",
    "requirements": "正看護師資格必須、病棟経験2年以上優遇",
    "benefits": "社会保険完備、賞与あり、研修制度充実",
    "location": "東京都世田谷区桜新町2-15-8",
    "phone": "03-1234-5678",
    "maxBadges": 1,
    "isFixed": false
  },
  {
    "id": 10,
    "img": `${PUBLIC_PATH}/sample-img/06.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/06-small.jpg`,
    "title": "鈴木耳鼻科クリニック",
    "subtitle": "問診記録、アレルギー検査補助、診療準備、備品整理",
    "start": "2025-10-22T09:00:00",
    "end": "2025-10-22T17:00:00",
    "hourPrice": 1850,
    "description": "アレルギー検査を専門とする診療日のサポート業務です。問診内容の記録、各種アレルギー検査の補助、診療器具の準備など、専門性の高い業務に携わっていただきます。高時給で専門スキルを活かせるポジションです。",
    "requirements": "正看護師資格、アレルギー検査経験者優遇",
    "benefits": "高時給、専門スキル習得可能、単発OK",
    "location": "埼玉県さいたま市大宮区桜木町1-7-5",
    "phone": "048-765-4321",
    "maxBadges": 5,
    "isFixed": false
  },
  {
    "id": 11,
    "img": `${PUBLIC_PATH}/sample-img/01.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/01-small.jpg`,
    "title": "田中内科医院",
    "subtitle": "採血、バイタルチェック、環境整備、物品補充",
    "start": "2025-10-25T15:00:00",
    "end": "2025-10-25T23:30:00",
    "hourPrice": 1600,
    "description": "内科クリニックでの夕方から夜間にかけての勤務です。採血やバイタルチェックなどの基本的な看護技術に加え、診療環境の整備や医療材料の補充などもお任せします。仕事とプライベートを両立させたい方におすすめのシフトです。",
    "requirements": "正看護師資格、採血スキル必須",
    "benefits": "夕方からの勤務、週2回～相談可、昇給あり",
    "location": "神奈川県横浜市港北区日吉3-22-1",
    "phone": "045-987-6543",
    "maxBadges": 3,
    "isFixed": false
  },
  {
    "id": 12,
    "img": `${PUBLIC_PATH}/sample-img/07.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/07-small.jpg`,
    "title": "佐藤整形外科",
    "subtitle": "リハビリ補助、記録管理、患者対応、清掃業務",
    "start": "2025-11-02T09:00:00",
    "end": "2025-11-02T18:00:00",
    "hourPrice": 1450,
    "description": "整形外科クリニックでリハビリ補助と記録管理中心のお仕事です。患者様への対応や院内清掃業務も行っていただきます。未経験でも基礎から丁寧に指導しますので安心です。",
    "requirements": "看護師または准看護師資格、整形外科経験不問",
    "benefits": "研修制度充実、交通費支給、賞与あり",
    "location": "千葉県船橋市本町4-10-9",
    "phone": "047-123-4567",
    "maxBadges": 2,
    "isFixed": false
  },
  {
    "id": 13,
    "img": `${PUBLIC_PATH}/sample-img/08.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/08-small.jpg`,
    "title": "高橋クリニック",
    "subtitle": "外来受付、電子カルテ入力、健康診断補助",
    "start": "2025-11-07T08:30:00",
    "end": "2025-11-07T14:30:00",
    "hourPrice": 1400,
    "description": "地域密着のクリニックで外来受付と健康診断補助を担当していただきます。短時間勤務なので主婦やWワークにもおすすめです。",
    "requirements": "正看護師資格、電子カルテ操作経験尚可",
    "benefits": "短時間勤務、Wワーク可、交通費支給",
    "location": "東京都品川区大井町1-2-3",
    "phone": "03-5678-1234",
    "maxBadges": 1,
    "isFixed": false
  },
  {
    "id": 14,
    "img": `${PUBLIC_PATH}/sample-img/09.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/09-small.jpg`,
    "title": "村上小児科",
    "subtitle": "予防接種補助、保護者対応、診察補助",
    "start": "2025-11-11T09:00:00",
    "end": "2025-11-11T14:00:00",
    "hourPrice": 1550,
    "description": "小児科クリニックでの予防接種サポートおよび保護者の対応業務です。子供好きな方・対応力重視の職場です。",
    "requirements": "看護師資格、予防接種業務経験歓迎",
    "benefits": "お昼まで勤務、こども好き歓迎、制服貸与",
    "location": "東京都練馬区豊玉上1-22-3",
    "phone": "03-7654-3210",
    "maxBadges": 8,
    "isFixed": false
  },
  {
    "id": 15,
    "img": `${PUBLIC_PATH}/sample-img/10.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/10-small.jpg`,
    "title": "岡本精神科病院",
    "subtitle": "病棟看護、服薬管理、精神科対応",
    "start": "2025-11-15T09:00:00",
    "end": "2025-11-15T17:00:00",
    "hourPrice": 1720,
    "description": "精神科病院での病棟看護および服薬管理業務です。患者様の精神面をサポートするやりがいのある仕事です。",
    "requirements": "看護師資格、精神科経験者優遇",
    "benefits": "精神科研修充実、残業なし、駐車場完備",
    "location": "東京都北区赤羽南1-8-5",
    "phone": "03-8765-4321",
    "maxBadges": 3,
    "isFixed": false
  },
  {
    "id": 16,
    "img": `${PUBLIC_PATH}/sample-img/11.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/11-small.jpg`,
    "title": "石井訪問看護ステーション",
    "subtitle": "訪問看護、バイタルチェック、服薬支援",
    "start": "2025-11-19T09:00:00",
    "end": "2025-11-19T16:00:00",
    "hourPrice": 2000,
    "description": "自宅への訪問看護業務です。移動ありですが高時給で体力に自信のある方歓迎。服薬支援等も行います。",
    "requirements": "正看護師資格、運転免許必須",
    "benefits": "高時給、直行直帰OK、制服貸与",
    "location": "埼玉県川口市栄町3-2-1",
    "phone": "048-998-7890",
    "maxBadges": 7,
    "isFixed": false
  },
  {
    "id": 17,
    "img": `${PUBLIC_PATH}/sample-img/12.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/12-small.jpg`,
    "title": "佐々木眼科医院",
    "subtitle": "検査補助、患者案内、点眼指導",
    "start": "2025-11-23T08:30:00",
    "end": "2025-11-23T16:30:00",
    "hourPrice": 1370,
    "description": "眼科医院での検査補助や患者の案内・点眼薬指導業務です。眼科未経験OK、丁寧に教えます。",
    "requirements": "看護師または准看護師資格",
    "benefits": "未経験OK、残業なし、有給あり",
    "location": "東京都杉並区高円寺北5-14-7",
    "phone": "03-6543-2109",
    "maxBadges": 6,
    "isFixed": false
  },
  {
    "id": 18,
    "img": `${PUBLIC_PATH}/sample-img/13.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/13-small.jpg`,
    "title": "今井クリニック",
    "subtitle": "健診サポート、採血業務、問診記録",
    "start": "2025-11-26T09:00:00",
    "end": "2025-11-26T17:00:00",
    "hourPrice": 1700,
    "description": "健診・採血業務中心のクリニックです。記録業務もお任せします。未経験でも応募可。",
    "requirements": "看護師資格、採血業務経験歓迎",
    "benefits": "交通費支給、制服貸与、単発OK",
    "location": "東京都新宿区西新宿2-10-1",
    "phone": "03-1122-3344",
    "maxBadges": 5,
    "isFixed": false
  },
  {
    "id": 19,
    "img": `${PUBLIC_PATH}/sample-img/14.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/14-small.jpg`,
    "title": "松本整形外科",
    "subtitle": "リハビリ助手、患者誘導、記録精査",
    "start": "2025-11-30T08:30:00",
    "end": "2025-11-30T16:00:00",
    "hourPrice": 1390,
    "description": "整形外科リハビリ助手として患者誘導・記録業務中心のお仕事です。初心者歓迎です。",
    "requirements": "看護師または准看護師資格",
    "benefits": "交通費全額支給、制服貸与、土日休み",
    "location": "千葉県松戸市根本5-9-2",
    "phone": "047-223-9876",
    "maxBadges": 2,
    "isFixed": false
  },
  {
    "id": 20,
    "img": `${PUBLIC_PATH}/sample-img/15.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/15-small.jpg`,
    "title": "小川クリニック",
    "subtitle": "発熱外来補助、問診記録、消毒作業",
    "start": "2025-12-04T14:00:00",
    "end": "2025-12-04T20:00:00",
    "hourPrice": 1680,
    "description": "発熱患者対応が中心の外来診療補助の仕事です。消毒作業もお任せします。",
    "requirements": "看護師資格、感染症対策意識ある方歓迎",
    "benefits": "高時給、単発OK、交通費支給",
    "location": "神奈川県川崎市高津区溝口3-8-2",
    "phone": "044-123-6547",
    "maxBadges": 4,
    "isFixed": false
  },
  {
    "id": 21,
    "img": `${PUBLIC_PATH}/sample-img/16.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/16-small.jpg`,
    "title": "平井病院",
    "subtitle": "病棟夜勤、急変対応、記録管理",
    "start": "2025-12-08T19:00:00",
    "end": "2025-12-09T08:00:00",
    "hourPrice": 2100,
    "description": "夜勤での病棟業務（急変対応・記録業務）中心、高収入シフトとなります。夜勤経験者歓迎。",
    "requirements": "正看護師資格、夜勤経験必須",
    "benefits": "夜勤手当高額、仮眠室あり、交通費全額支給",
    "location": "東京都江戸川区平井4-21-6",
    "phone": "03-1122-5555",
    "maxBadges": 6,
    "isFixed": false
  },
  {
    "id": 22,
    "img": `${PUBLIC_PATH}/sample-img/17.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/17-small.jpg`,
    "title": "八木内科クリニック",
    "subtitle": "外来受付、バイタル測定、問診補助",
    "start": "2025-12-12T08:00:00",
    "end": "2025-12-12T12:00:00",
    "hourPrice": 1350,
    "description": "外来受付からバイタル測定までのシフトです。時短勤務、主婦歓迎です。",
    "requirements": "看護師または准看護師資格",
    "benefits": "短時間勤務、交通費支給、制服貸与",
    "location": "東京都目黒区自由が丘1-16-11",
    "phone": "03-3344-2211",
    "maxBadges": 1,
    "isFixed": false
  },
  {
    "id": 23,
    "img": `${PUBLIC_PATH}/sample-img/18.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/18-small.jpg`,
    "title": "島田ホームクリニック",
    "subtitle": "訪問診療補助、バイタル管理、環境整備",
    "start": "2025-12-15T13:00:00",
    "end": "2025-12-15T17:30:00",
    "hourPrice": 1580,
    "description": "在宅訪問診療の補助・バイタル管理中心。訪問経験者優遇、体力に自信ある方歓迎。",
    "requirements": "正看護師資格、運転免許尚可",
    "benefits": "交通費全額支給、制服貸与、単発OK",
    "location": "東京都板橋区板橋1-16-3",
    "phone": "03-4455-6677",
    "maxBadges": 5,
    "isFixed": false
  },
  {
    "id": 24,
    "img": `${PUBLIC_PATH}/sample-img/19.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/19-small.jpg`,
    "title": "佐藤耳鼻咽喉科",
    "subtitle": "検査補助、診察介助、器具洗浄",
    "start": "2025-12-20T09:00:00",
    "end": "2025-12-20T17:00:00",
    "hourPrice": 1410,
    "description": "耳鼻咽喉科での検査・診察補助のお仕事です。未経験でも丁寧に指導します。",
    "requirements": "看護師または准看護師資格",
    "benefits": "未経験OK、交通費支給、制服貸与",
    "location": "埼玉県さいたま市浦和区仲町4-6-2",
    "phone": "048-876-2222",
    "maxBadges": 4,
    "isFixed": false
  },
  {
    "id": 25,
    "img": `${PUBLIC_PATH}/sample-img/20.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/20-small.jpg`,
    "title": "長谷川小児科医院",
    "subtitle": "診察補助、予防接種補助、カルテ入力",
    "start": "2025-12-25T08:30:00",
    "end": "2025-12-25T14:00:00",
    "hourPrice": 1530,
    "description": "小児科クリニックでの診察・予防接種補助、カルテ入力業務です。こども好きの方におすすめ。",
    "requirements": "看護師資格、予防接種業務経験者歓迎",
    "benefits": "時短勤務、お昼まで、制服貸与",
    "location": "東京都足立区千住4-12-8",
    "phone": "03-5566-7788",
    "maxBadges": 7,
    "isFixed": false
  }
]

export const SAMPLE_EXTRA_CARDS: Card[] = [
  {
    "id": 26,
    "img": `${PUBLIC_PATH}/sample-img/03.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/03-small.jpg`,
    "title": "野村レディースクリニック",
    "subtitle": "婦人科外来、問診対応、採血業務",
    "start": "2026-01-02T09:00:00",
    "end": "2026-01-02T15:00:00",
    "hourPrice": 1650,
    "description": "婦人科専門クリニックで、定期検診や不妊治療を受ける患者様のサポートを行います。問診時には悩みをじっくり聞き、採血やバイタル測定なども担当。女性のみの職場なので人間関係も安心です。カウンセリングや生活指導など予防医学の知識も深まります。初めて婦人科分野にチャレンジする方には先輩スタッフが丁寧に指導しますので、安心してご応募ください。長期勤務やWワーク希望にも柔軟に対応します。",
    "requirements": "看護師資格、婦人科経験歓迎",
    "benefits": "交通費全額支給、制服貸与、時短OK",
    "location": "東京都世田谷区用賀5-6-7",
    "phone": "03-1111-2233",
    "maxBadges": 3,
    "isFixed": false
  },
  {
    "id": 27,
    "img": `${PUBLIC_PATH}/sample-img/05.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/05-small.jpg`,
    "title": "横浜グリーンクリニック",
    "subtitle": "糖尿病内科補助、健康相談、記録業務",
    "start": "2026-01-04T08:00:00",
    "end": "2026-01-04T13:30:00",
    "hourPrice": 1430,
    "description": "糖尿病患者さんへの生活指導からバイタルチェック・検査記録まで多岐に渡る業務内容です。外来診療だけではなく、栄養指導や運動習慣の相談など予防医学にも力を入れた職場です。患者様一人ひとりとじっくり関われるため、やりがいと達成感が得られます。電子カルテ入力や血糖測定器の扱いも学べます。働きやすさを重視した環境で、子育て中やブランクありの方も無理なく復職できます。",
    "requirements": "看護師資格、内科経験者尚可",
    "benefits": "短時間OK、交通費支給、資格手当",
    "location": "神奈川県横浜市中区新山下4-9-1",
    "phone": "045-223-4567",
    "maxBadges": 7,
    "isFixed": false
  },
  {
    "id": 28,
    "img": `${PUBLIC_PATH}/sample-img/12.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/12-small.jpg`,
    "title": "杉並訪問看護ステーション",
    "subtitle": "訪問看護、服薬管理、バイタル記録",
    "start": "2026-01-06T09:00:00",
    "end": "2026-01-06T17:00:00",
    "hourPrice": 1800,
    "description": "地域在宅医療の現場で、ご自宅療養中の高齢者や障がい者の方へ定期訪問看護を行います。バイタルチェックや服薬管理、医師の指示に基づく処置、記録業務などを担当します。自転車での移動が中心で、道順もすぐに慣れます。在宅医療未経験者にも基礎から研修があるので安心です。アットホームな雰囲気とチームワーク重視の職場でじっくり成長したい方におすすめです。",
    "requirements": "正看護師資格、運転免許不要",
    "benefits": "高時給、制服貸与、交通費支給",
    "location": "東京都杉並区今川2-14-8",
    "phone": "03-4321-5678",
    "maxBadges": 5,
    "isFixed": false
  },
  {
    "id": 29,
    "img": `${PUBLIC_PATH}/sample-img/18.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/18-small.jpg`,
    "title": "三浦内科医院",
    "subtitle": "健康診断補助、採血、患者対応",
    "start": "2026-01-08T09:00:00",
    "end": "2026-01-08T13:00:00",
    "hourPrice": 1500,
    "description": "近隣住民の定期健康診断を中心に、採血・各種測定・体調相談など幅広い業務があります。午前だけ勤務で無理なく続けやすい職場。コミュニケーション重視で気軽に質問や相談ができる環境です。主婦・Wワークも歓迎、子育て中の方も働きやすいよう配慮しています。未経験でも一から指導しますので安心してご応募ください。",
    "requirements": "看護師資格、採血スキル必須",
    "benefits": "交通費支給、制服貸与、午前勤務",
    "location": "千葉県市川市南行徳1-3-5",
    "phone": "047-234-5678",
    "maxBadges": 8,
    "isFixed": false
  },
  {
    "id": 30,
    "img": `${PUBLIC_PATH}/sample-img/08.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/08-small.jpg`,
    "title": "新宿山田クリニック",
    "subtitle": "採血補助、診療器具洗浄、外来受付",
    "start": "2026-01-10T10:00:00",
    "end": "2026-01-10T14:00:00",
    "hourPrice": 1380,
    "description": "新宿駅近のクリニックで、午前外来を中心に採血や検査準備・器具洗浄業務などを担当します。来院患者様の受付対応のほか、体調相談にも対応。忙しい日でもチームで協力しながら乗り切れる、風通しの良い職場です。経験が浅い方も丁寧な研修を受けられるので安心です。",
    "requirements": "看護師または准看護師資格",
    "benefits": "交通費支給、Wワーク可、午後のみOK",
    "location": "東京都新宿区小川町2-17-1",
    "phone": "03-3456-7890",
    "maxBadges": 2,
    "isFixed": false
  },
  {
    "id": 31,
    "img": `${PUBLIC_PATH}/sample-img/04.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/04-small.jpg`,
    "title": "小川歯科医院",
    "subtitle": "診察補助、院内清掃、環境整備",
    "start": "2026-01-12T09:00:00",
    "end": "2026-01-12T15:00:00",
    "hourPrice": 1410,
    "description": "歯科診療所での診察補助および院内環境整備のお仕事です。器具出しや診察室・待合室の清掃、患者応対などが主な業務。受付業務を兼任する場合もあります。ベテラン歯科医師の指導のもと、未経験者にも丁寧に教えます。ブランクのある方や主婦・学生も働きやすい柔軟シフトです。",
    "requirements": "看護師または准看護師資格",
    "benefits": "短時間勤務、交通費全額支給、制服貸与",
    "location": "東京都小平市学園東町5-1-9",
    "phone": "042-567-2345",
    "maxBadges": 7,
    "isFixed": false
  },
  {
    "id": 32,
    "img": `${PUBLIC_PATH}/sample-img/01.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/01-small.jpg`,
    "title": "いずみ小児科医院",
    "subtitle": "診察補助、予防接種、カルテ入力",
    "start": "2026-01-14T08:30:00",
    "end": "2026-01-14T13:00:00",
    "hourPrice": 1540,
    "description": "地域密着型の小児科医院で、発熱患者対応・予防接種補助など子どもと直接関われる仕事です。保護者とのコミュニケーションも多く、やりがいを感じられます。電子カルテ操作や定期業務も丁寧に教えますので、未経験者も安心です。午前のみ、週1〜OK、主婦やWワークの方も大歓迎です。",
    "requirements": "看護師資格、予防接種業務経験尚可",
    "benefits": "お昼まで勤務、交通費支給、制服貸与",
    "location": "東京都国分寺市泉町1-23-4",
    "phone": "042-568-1234",
    "maxBadges": 1,
    "isFixed": false
  },
  {
    "id": 33,
    "img": `${PUBLIC_PATH}/sample-img/19.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/19-small.jpg`,
    "title": "佐藤皮膚科クリニック",
    "subtitle": "診察介助、問診記録、患者案内",
    "start": "2026-01-16T09:00:00",
    "end": "2026-01-16T17:00:00",
    "hourPrice": 1600,
    "description": "皮膚科外来にて新患・再診患者の問診補助や診察介助を行います。肌トラブルや慢性疾患を持つ患者様への丁寧な案内とサポートが重要です。記録管理は専用システムで教育。未経験の分野でもしっかりスキルアップできます。親しみやすい雰囲気の職場で相談しやすさが魅力です。",
    "requirements": "看護師資格、皮膚科経験歓迎",
    "benefits": "残業ほぼなし、交通費全額支給、賞与あり",
    "location": "東京都葛飾区青戸2-5-12",
    "phone": "03-2900-1234",
    "maxBadges": 6,
    "isFixed": false
  },
  {
    "id": 34,
    "img": `${PUBLIC_PATH}/sample-img/15.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/15-small.jpg`,
    "title": "吉田眼科クリニック",
    "subtitle": "視力検査補助、点眼指導、受付業務",
    "start": "2026-01-18T09:00:00",
    "end": "2026-01-18T15:00:00",
    "hourPrice": 1390,
    "description": "眼科クリニックで視力検査時の補助や点眼薬の使用指導など患者様の不安を取り除く業務です。受付対応とカルテ整理も担当します。丁寧な指導体制なので眼科初挑戦でも安心。主婦・シニア看護師歓迎、短時間勤務も可能です。",
    "requirements": "看護師資格、眼科未経験可",
    "benefits": "制服貸与、交通費全額支給、短時間OK",
    "location": "東京都中野区東中野8-7-3",
    "phone": "03-5555-5678",
    "maxBadges": 4,
    "isFixed": false
  },
  {
    "id": 35,
    "img": `${PUBLIC_PATH}/sample-img/07.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/07-small.jpg`,
    "title": "村上整形外科",
    "subtitle": "リハビリ補助、記録入力、患者誘導",
    "start": "2026-01-20T10:00:00",
    "end": "2026-01-20T18:00:00",
    "hourPrice": 1500,
    "description": "整形外科リハビリ助手として、患者さんのリハメニューの準備や誘導、リハ記録の入力業務まで幅広く担当。スタッフ間のサポートが充実しているため、初心者も安心して働けます。研修制度があり、長期的なキャリア形成を目指したい方にも最適です。",
    "requirements": "看護師資格、リハビリ経験者歓迎",
    "benefits": "交通費支給、制服貸与、社会保険完備",
    "location": "千葉県松戸市北松戸3-9-2",
    "phone": "047-223-1111",
    "maxBadges": 8,
    "isFixed": false
  },
  {
    "id": 36,
    "img": `${PUBLIC_PATH}/sample-img/17.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/17-small.jpg`,
    "title": "本田内科医院",
    "subtitle": "採血、バイタル測定、問診記録",
    "start": "2026-01-22T09:00:00",
    "end": "2026-01-22T13:00:00",
    "hourPrice": 1480,
    "description": "駅近の内科クリニックで、採血・バイタル測定を行いながら患者様の症状や生活習慣の聞き取りも担当します。午前勤務のみ、未経験者歓迎。丁寧な指導で一人ひとりに合ったペースで成長できます。主婦・ブランク復帰希望の方も活躍中です。",
    "requirements": "看護師資格、採血スキル尚可",
    "benefits": "交通費全額支給、制服貸与、昇給あり",
    "location": "東京都墨田区両国1-6-8",
    "phone": "03-1222-3344",
    "maxBadges": 3,
    "isFixed": false
  },
  {
    "id": 37,
    "img": `${PUBLIC_PATH}/sample-img/11.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/11-small.jpg`,
    "title": "田辺メンタルクリニック",
    "subtitle": "カウンセリング補助、服薬管理、記録業務",
    "start": "2026-01-24T13:00:00",
    "end": "2026-01-24T18:00:00",
    "hourPrice": 1720,
    "description": "精神科クリニックでのカウンセリング補助や服薬管理業務。患者様の心理面サポートに興味ある方歓迎。電子カルテでの記録や医師指示の実施体制も充実。未経験者も安心して学べる環境です。働きやすい柔軟シフトで家庭やプライベートとの両立も可能です。",
    "requirements": "看護師資格、精神科経験者尚可",
    "benefits": "交通費支給、制服貸与、研修制度充実",
    "location": "東京都目黒区上目黒8-2-9",
    "phone": "03-6547-1234",
    "maxBadges": 1,
    "isFixed": false
  },
  {
    "id": 38,
    "img": `${PUBLIC_PATH}/sample-img/20.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/20-small.jpg`,
    "title": "三宅皮膚科医院",
    "subtitle": "問診票管理、診察補助、器具洗浄",
    "start": "2026-01-26T09:00:00",
    "end": "2026-01-26T17:00:00",
    "hourPrice": 1450,
    "description": "皮膚科専用クリニックで、患者対応・問診票管理・診察介助・器具滅菌作業まで一貫して担当します。毎月研修があり新しい知識をどんどん吸収できます。家庭やプライベートの都合に合わせて働き方も柔軟に調整可能。未経験者も先輩がマンツーマンでサポートします。",
    "requirements": "看護師または准看護師資格",
    "benefits": "研修制度充実、交通費全額支給、制服貸与",
    "location": "埼玉県川越市鴨田町2-10-4",
    "phone": "049-333-5678",
    "maxBadges": 8,
    "isFixed": false
  },
  {
    "id": 39,
    "img": `${PUBLIC_PATH}/sample-img/09.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/09-small.jpg`,
    "title": "中村小児科医院",
    "subtitle": "健診補助、診察介助、保護者対応",
    "start": "2026-01-28T08:30:00",
    "end": "2026-01-28T14:30:00",
    "hourPrice": 1530,
    "description": "小児科クリニックでの定期健診補助や診察サポート、保護者対応業務です。育児知識や小児ケアのノウハウも自然と身につきます。電子カルテでの記録や園児対応の研修も充実しているため、ブランクのある方でも安心して始められます。子育て中の方大歓迎！",
    "requirements": "看護師資格、予防接種経験者尚可",
    "benefits": "交通費支給、制服貸与、お昼まで",
    "location": "東京都大田区南雪谷2-14-2",
    "phone": "03-5566-7890",
    "maxBadges": 5,
    "isFixed": false
  },
  {
    "id": 40,
    "img": `${PUBLIC_PATH}/sample-img/16.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/16-small.jpg`,
    "title": "川口リハビリ整形外科",
    "subtitle": "リハビリ補助、環境整備、記録入力",
    "start": "2026-01-30T09:00:00",
    "end": "2026-01-30T15:00:00",
    "hourPrice": 1470,
    "description": "リハビリ助手業務、院内環境の整備や診療記録入力、患者様対応まで一貫して担当します。スムーズな誘導や手厚いケアで患者様を支援。未経験やブランク有でも研修ありで安心して働けます。現場スタッフの手厚いサポートも魅力です。",
    "requirements": "看護師または准看護師資格",
    "benefits": "交通費全額支給、制服貸与、短時間勤務OK",
    "location": "埼玉県川口市青木町1-2-1",
    "phone": "048-998-2345",
    "maxBadges": 7,
    "isFixed": false
  },
  {
    "id": 41,
    "img": `${PUBLIC_PATH}/sample-img/02.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/02-small.jpg`,
    "title": "西村耳鼻咽喉科",
    "subtitle": "検査準備、患者案内、器具洗浄",
    "start": "2026-02-01T09:00:00",
    "end": "2026-02-01T16:00:00",
    "hourPrice": 1420,
    "description": "耳鼻咽喉科での検査補助、患者誘導、診察器具の洗浄などを担当します。未経験者もゼロから教えます。月一度の院内勉強会、チームで相談し合える体制が整っているので安心。短時間勤務も応相談です。",
    "requirements": "看護師資格、耳鼻科未経験可",
    "benefits": "交通費支給、制服貸与、残業ほぼなし",
    "location": "東京都墨田区錦糸町2-16-7",
    "phone": "03-7654-2222",
    "maxBadges": 1,
    "isFixed": false
  },
  {
    "id": 42,
    "img": `${PUBLIC_PATH}/sample-img/14.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/14-small.jpg`,
    "title": "白井眼科医院",
    "subtitle": "検査補助、クリニック清掃、患者対応",
    "start": "2026-02-03T08:30:00",
    "end": "2026-02-03T16:30:00",
    "hourPrice": 1360,
    "description": "眼科検査補助、院内清掃や受付業務を担当します。未経験歓迎、クリーンな施設環境で気持ちよく働けます。スタッフ同士のコミュニケーションも活発で、人間関係で悩む心配なし。子育て中の方やシニアも活躍しています。",
    "requirements": "看護師または准看護師資格",
    "benefits": "制服貸与、交通費支給、有給あり",
    "location": "千葉県白井市大松5-6-1",
    "phone": "047-123-2222",
    "maxBadges": 3,
    "isFixed": false
  },
  {
    "id": 43,
    "img": `${PUBLIC_PATH}/sample-img/13.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/13-small.jpg`,
    "title": "宮本ホームクリニック",
    "subtitle": "訪問診療、バイタル管理、記録整理",
    "start": "2026-02-05T13:00:00",
    "end": "2026-02-05T18:00:00",
    "hourPrice": 1760,
    "description": "在宅患者さんの訪問診療補助やバイタル管理・服薬支援、診療内容の記録整理などを行います。車両移動で体力が必要ですが高待遇。訪問看護経験者は優遇、未経験も研修でフォロー。直行直帰OKで働きやすさ満点です。",
    "requirements": "正看護師資格、運転免許必須",
    "benefits": "交通費支給、制服貸与、単発OK",
    "location": "東京都葛飾区西新小岩4-6-9",
    "phone": "03-3344-9911",
    "maxBadges": 5,
    "isFixed": false
  },
  {
    "id": 44,
    "img": `${PUBLIC_PATH}/sample-img/06.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/06-small.jpg`,
    "title": "坂本整形外科",
    "subtitle": "リハビリ助手、記録管理、患者案内",
    "start": "2026-02-07T09:00:00",
    "end": "2026-02-07T17:00:00",
    "hourPrice": 1440,
    "description": "整形外科病院で、各種リハビリの補助や患者誘導・記録管理を担当します。経験豊富なスタッフが揃っているので、未経験者やブランク復帰も手厚くサポートします。医師との連携も円滑でストレスなく働けます。資格取得支援制度あり。",
    "requirements": "看護師または准看護師資格",
    "benefits": "交通費全額支給、制服貸与、社会保険あり",
    "location": "千葉県船橋市海神町4-10-7",
    "phone": "047-987-8765",
    "maxBadges": 8,
    "isFixed": false
  },
  {
    "id": 45,
    "img": `${PUBLIC_PATH}/sample-img/10.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/10-small.jpg`,
    "title": "高田耳鼻科クリニック",
    "subtitle": "患者案内、問診補助、器具洗浄",
    "start": "2026-02-09T09:00:00",
    "end": "2026-02-09T17:00:00",
    "hourPrice": 1400,
    "description": "耳鼻科クリニックでの患者案内、問診の聞き取り補助、診察器具の準備および洗浄業務です。明るくアットホームな環境で働きやすさ抜群。電子カルテ入力も丁寧に教えます。週1回から相談可能でプライベートを大切にしたい方にもピッタリです。",
    "requirements": "看護師または准看護師資格",
    "benefits": "制服貸与、交通費全額支給、残業なし",
    "location": "東京都品川区中延1-9-2",
    "phone": "03-5678-4322",
    "maxBadges": 4,
    "isFixed": false
  },
  {
    "id": 46,
    "img": `${PUBLIC_PATH}/sample-img/09.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/09-small.jpg`,
    "title": "前田小児科医院",
    "subtitle": "予防接種補助、カルテ入力、保護者説明",
    "start": "2026-02-11T08:30:00",
    "end": "2026-02-11T14:30:00",
    "hourPrice": 1520,
    "description": "地域密着型の小児科医院で、予防接種の補助やカルテ入力、保護者への説明業務など幅広く担当します。子どもと触れ合うのが好きな方には最適。医師・スタッフ同士で協力し合い、チームワーク抜群の職場です。育児経験がある方も大歓迎です。",
    "requirements": "看護師資格、こども対応力歓迎",
    "benefits": "制服貸与、交通費支給、お昼まで",
    "location": "東京都世田谷区奥沢2-22-10",
    "phone": "03-2222-3344",
    "maxBadges": 4,
    "isFixed": false
  },
  {
    "id": 47,
    "img": `${PUBLIC_PATH}/sample-img/19.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/19-small.jpg`,
    "title": "石田内科病院",
    "subtitle": "病棟看護、配薬準備、記録入力",
    "start": "2026-02-13T09:00:00",
    "end": "2026-02-13T19:00:00",
    "hourPrice": 1780,
    "description": "内科病棟業務として、バイタル測定・記録管理・配薬補助・チーム医療の一員として活躍していただきます。教育体制も整っており資格取得やスキルアップも支援します。医師・看護師・事務スタッフが協力し合う環境で、長く安心して勤務可能。",
    "requirements": "正看護師資格、病棟経験歓迎",
    "benefits": "交通費全額支給、社会保険あり、賞与あり",
    "location": "東京都江戸川区西葛西4-17-1",
    "phone": "03-1122-8899",
    "maxBadges": 2,
    "isFixed": false
  },
  {
    "id": 48,
    "img": `${PUBLIC_PATH}/sample-img/13.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/13-small.jpg`,
    "title": "田口整形外科",
    "subtitle": "リハビリ助手、記録入力、患者対応",
    "start": "2026-02-15T09:00:00",
    "end": "2026-02-15T17:00:00",
    "hourPrice": 1410,
    "description": "整形外科病院のリハビリテーション部門での助手業務です。リハメニューの準備、記録管理、患者さんの誘導などを担当。リハビリ未経験者も安心の研修制度があり、ブランク復帰も支援しています。",
    "requirements": "看護師または准看護師資格",
    "benefits": "交通費全額支給、制服貸与、賞与あり",
    "location": "千葉県浦安市堀江2-18-12",
    "phone": "047-999-2222",
    "maxBadges": 6,
    "isFixed": false
  },
  {
    "id": 49,
    "img": `${PUBLIC_PATH}/sample-img/06.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/06-small.jpg`,
    "title": "広瀬内科医院",
    "subtitle": "採血、バイタル測定、環境管理",
    "start": "2026-02-17T09:00:00",
    "end": "2026-02-17T15:00:00",
    "hourPrice": 1640,
    "description": "内科診療所で採血やバイタル測定、待合・診察室の環境管理業務など幅広く担当します。丁寧な研修があり未経験者も歓迎。主婦・シニアでも働きやすく、勤務形態の相談が可能です。患者様との距離も近い、温かいクリニックです。",
    "requirements": "看護師資格、採血スキル尚可",
    "benefits": "交通費支給、制服貸与、短時間勤務OK",
    "location": "東京都西東京市南町4-6-22",
    "phone": "042-511-2345",
    "maxBadges": 8,
    "isFixed": false
  },
  {
    "id": 50,
    "img": `${PUBLIC_PATH}/sample-img/18.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/18-small.jpg`,
    "title": "青木メンタルクリニック",
    "subtitle": "服薬管理、問診記録、患者対応",
    "start": "2026-02-19T13:00:00",
    "end": "2026-02-19T18:00:00",
    "hourPrice": 1730,
    "description": "地域に信頼されるメンタルクリニックです。患者様の服薬管理、問診記録、生活指導など細やかな心遣いが求められる職場です。チームで連携しながら多職種協働で患者様をサポート。未経験・ブランク復帰も積極支援。",
    "requirements": "看護師資格、精神科経験者歓迎",
    "benefits": "交通費全額支給、制服貸与、社会保険あり",
    "location": "東京都大田区大森西2-9-1",
    "phone": "03-6547-2234",
    "maxBadges": 7,
    "isFixed": false
  },
  {
    "id": 51,
    "img": `${PUBLIC_PATH}/sample-img/20.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/20-small.jpg`,
    "title": "松浦耳鼻科医院",
    "subtitle": "検査補助、患者案内、器具滅菌",
    "start": "2026-02-21T09:00:00",
    "end": "2026-02-21T16:00:00",
    "hourPrice": 1430,
    "description": "耳鼻科クリニックで検査、診察時の患者さんの誘導・案内・器具滅菌作業を担当。スタッフ間のフォロー体制も充実していて働きやすい職場です。未経験者への研修も万全なので初めてでも心配ありません。",
    "requirements": "看護師資格、耳鼻科経験者尚可",
    "benefits": "交通費全額支給、制服貸与、有給あり",
    "location": "神奈川県川崎市多摩区登戸3-14-10",
    "phone": "044-567-1111",
    "maxBadges": 3,
    "isFixed": false
  },
  {
    "id": 52,
    "img": `${PUBLIC_PATH}/sample-img/02.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/02-small.jpg`,
    "title": "石川小児科医院",
    "subtitle": "予防接種補助、診察記録、保護者説明",
    "start": "2026-02-23T08:30:00",
    "end": "2026-02-23T14:30:00",
    "hourPrice": 1550,
    "description": "小児科クリニックでの予防接種サポート、診察記録入力、保護者の不安解消のための説明業務です。地域密着の温かい雰囲気の職場で、ママさん看護師やWワーク希望も歓迎。新卒・未経験者もしっかり指導するので安心です。",
    "requirements": "看護師資格、こども対応力歓迎",
    "benefits": "交通費支給、制服貸与、お昼まで",
    "location": "東京都世田谷区瀬田2-22-9",
    "phone": "03-2222-6492",
    "maxBadges": 5,
    "isFixed": false
  },
  {
    "id": 53,
    "img": `${PUBLIC_PATH}/sample-img/08.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/08-small.jpg`,
    "title": "和田内科クリニック",
    "subtitle": "診察介助、採血、記録入力",
    "start": "2026-02-25T09:00:00",
    "end": "2026-02-25T17:00:00",
    "hourPrice": 1620,
    "description": "内科クリニックの外来診療補助担当として、患者応対、採血、記録入力など川の流れのように進めていきます。短時間勤務も可能で、育児ママも活躍中。ベテランスタッフが多数在籍、困った時はすぐにサポートがあります。働きやすい環境です。",
    "requirements": "看護師資格、内科経験歓迎",
    "benefits": "交通費支給、制服貸与、社会保険あり",
    "location": "東京都中野区中央3-22-10",
    "phone": "03-2222-9182",
    "maxBadges": 6,
    "isFixed": false
  },
  {
    "id": 54,
    "img": `${PUBLIC_PATH}/sample-img/12.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/12-small.jpg`,
    "title": "三木整形外科",
    "subtitle": "リハビリ補助、院内清掃、患者案内",
    "start": "2026-02-27T09:00:00",
    "end": "2026-02-27T17:00:00",
    "hourPrice": 1460,
    "description": "整形外科クリニックでのリハビリ助手として、患者誘導・院内清掃・記録管理など幅広く担当します。未経験でも充実した研修制度と先輩のサポートですぐ現場になじみます。院内は明るく居心地が良い環境。土日祝休みでプライベートも充実できます。",
    "requirements": "看護師または准看護師資格",
    "benefits": "交通費支給、制服貸与、土日祝休み",
    "location": "千葉県船橋市駿河台4-10-8",
    "phone": "047-823-5566",
    "maxBadges": 4,
    "isFixed": false
  },
  {
    "id": 55,
    "img": `${PUBLIC_PATH}/sample-img/15.jpg`,
    "imgSmall": `${PUBLIC_PATH}/sample-img/15-small.jpg`,
    "title": "大塚眼科クリニック",
    "subtitle": "検査補助、受付業務、点眼指導",
    "start": "2026-03-01T09:00:00",
    "end": "2026-03-01T15:00:00",
    "hourPrice": 1375,
    "description": "眼科クリニックでの一般検査補助業務を中心に、患者様への受付対応や点眼薬の指導なども行います。未経験者への指導やサポート体制が充実しています。残業もほぼなく、有給取得率も高いためワークライフバランスを大切にしたい方におすすめです。",
    "requirements": "看護師または准看護師資格",
    "benefits": "交通費支給、制服貸与、有給・残業なし",
    "location": "東京都文京区大塚1-3-7",
    "phone": "03-8833-1187",
    "maxBadges": 8,
    "isFixed": false
  }
]


function randInt(from: number, to: number): number {
  return Math.floor(Math.random() * (to - from + 1)) + from;
}

function shuffle<T>(array: T[]): T[] {
  // 非破壊的シャッフル
  return array.slice().sort(() => Math.random() - 0.5);
}

function randomFromArray<T>(array: T[], count: number): T[] {
  return shuffle(array).slice(0, count);
}
