#pragma once

#include "storage/wal/record/alter_table_entry_record.h"
#include "storage/wal/record/begin_transaction_record.h"
#include "storage/wal/record/checkpoint_record.h"
#include "storage/wal/record/commit_record.h"
#include "storage/wal/record/copy_table_record.h"
#include "storage/wal/record/create_catalog_entry_record.h"
#include "storage/wal/record/drop_catalog_entry_record.h"
#include "storage/wal/record/load_extension_record.h"
#include "storage/wal/record/node_deletion_record.h"
#include "storage/wal/record/node_update_record.h"
#include "storage/wal/record/rel_deletion_record.h"
#include "storage/wal/record/rel_detach_delete_record.h"
#include "storage/wal/record/rel_update_record.h"
#include "storage/wal/record/table_insertion_record.h"
#include "storage/wal/record/update_sequence_record.h"
#include "storage/wal/record/wal_record_base.h"
