export const TOKEN_EXPIRE_HOURS = 87600 // 10年
export const PUBLIC_PATH = ''
export const APP_NAME = 'NECO-ASOVI'
export const APP_SLUG = 'neco-asovi'
export const APP_CAPTION = 'Networked ECOsystem for Agentic AI SOVereign, In vitro.'
export const LOGO_IMG_SRC = `${PUBLIC_PATH}/neco-asovi/neco-asovi-white-256w.png`
export const LOGO_IMG_WHITE_SRC = `${PUBLIC_PATH}/neco-asovi/neco-asovi-white-m-128w.png`
export const LOGOTYPE_GREY = `${PUBLIC_PATH}/neco-asovi/neco-asovi-grey-t-256w.png`
export const LOGOTYPE_WHITE = `${PUBLIC_PATH}/neco-asovi/neco-asovi-white-t-256w.png`
export const API_BASE_URL = 'http://127.0.0.1:3910'
