export const TOKEN_EXPIRE_HOURS = 87600 // 10年
export const PUBLIC_PATH = ''
export const APP_NAME = 'MYCUTE'
export const APP_SLUG = 'mycute'
export const APP_CAPTION = 'Growing hearts of sweet AI kids, only for you.'
export const LOGO_IMG_SRC = `${PUBLIC_PATH}/mycute-white-256.png`
export const LOGO_IMG_WHITE_SRC = `${PUBLIC_PATH}/mycute-white-128.png`
export const LOGOTYPE_GREY = ``
export const LOGOTYPE_WHITE = ``
export const API_BASE_URL = 'http://127.0.0.1:3910'
