#!/bin/bash

# Configuration
INPUT_FILE="src/constants.rs"
OUTPUT_SDK="sdk-ts/src/generated_constants.ts"
OUTPUT_WEB="web/src/consts/generated_constants.ts"
CARGO_FILE="Cargo.toml"

# Function to generate header
write_header() {
    local target="$1"
    echo "/* eslint-disable */" > "$target"
    echo "/**" >> "$target"
    echo " * ATTENTION: This file is automatically generated by scripts/gen-ts-constants.sh" >> "$target"
    echo " * from src/constants.rs. Do not edit this file manually." >> "$target"
    echo " */" >> "$target"
    echo "" >> "$target"
}

# Ensure directories exist
mkdir -p "$(dirname "$OUTPUT_SDK")"
mkdir -p "$(dirname "$OUTPUT_WEB")"

write_header "$OUTPUT_SDK"
write_header "$OUTPUT_WEB"

# Parse constants
grep '^pub const' "$INPUT_FILE" | while read -r line; do
    # Clean line (remove CR if present)
    line=$(echo "$line" | tr -d '\r')
    
    # Extract name and value using regex
    name=$(echo "$line" | sed -E 's/pub const ([A-Z0-9_]+):.*/\1/')
    # Extract value, handling potential trailing comments or spaces before the semicolon
    value=$(echo "$line" | sed -E 's/.*= (.*);.*/\1/' | sed 's/[[:space:]]*$//')
    
    # Special handling for MYCUTE_VERSION (Single Source of Truth from Cargo.toml)
    if [[ "$name" == "MYCUTE_VERSION" ]]; then
        version=$(grep '^version =' "$CARGO_FILE" | head -n 1 | cut -d '"' -f 2)
        value="\"$version\""
    fi
    
    # Handle Rust concat! and env! macros for general case
    if [[ "$value" == *"env!(\"CARGO_PKG_VERSION\")"* ]]; then
        version=$(grep '^version =' "$CARGO_FILE" | head -n 1 | cut -d '"' -f 2)
        if [[ "$value" == *"concat!"* ]]; then
            prefix=$(echo "$value" | sed -E 's/concat!\("([^"]*)".*/\1/')
            value="\"$prefix$version\""
        else
            value="\"$version\""
        fi
    fi

    # Trim leading/trailing whitespace (without stripping quotes via xargs)
    value=$(echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

    # Skip values incompatible with TypeScript (e.g. Rust Enums with ::)
    if [[ "$value" == *"::"* ]]; then
        continue
    fi

    echo "export const $name = $value;" >> "$OUTPUT_SDK"
    echo "export const $name = $value;" >> "$OUTPUT_WEB"
done

# Function to generate footer
write_footer() {
    local target="$1"
    echo "" >> "$target"
    echo "/**" >> "$target"
    echo " * End of generated constants" >> "$target"
    echo " */" >> "$target"
}

write_footer "$OUTPUT_SDK"
write_footer "$OUTPUT_WEB"
